### ISSUE TITLE
feature request: wikipedia style citations

### ISSUE THREAD

**Issue by bcharles** [jamiely/citethis#1] opened 2016-05-18 17:35 UTC
It would be great to see wikipedia style citation templates among the output formats.  See
     https://en.wikipedia.org/wiki/Wikipedia:Citation_templates#Examples
     https://de.wikipedia.org/wiki/Benutzer:Rjh/wikipedia-reference-creator
or  https://github.com/abartov/cite4wiking

**Comment by JeffJacobson** [comment] 2022-04-15 14:55
It looks like this issue was resolved. I think someone just forgot to mark it as "closed". This feature seems to be working correctly when I just tried it. 

It thinks the author's name is "Dragging" for some reason, but that isn't specific to the "Wikipedia" style citation selection; it does that with all of them. (I only learned of this extension's existence a few minutes ago, so I don't know if this is expected behavior or not.)

Example output I currently get from the extension is below.

```mediawiki
<ref>{{cite web |url=https://github.com/jamiely/citethis/issues/1 |title=feature request: wikipedia style citations · Issue #1 · jamiely/citethis |last=undefined |first=Dragging |orig-date=April 15, 2022 |access-date=2022-04-15 }}</ref>
```

**Comment by BenMueller** [comment] 2022-04-15 18:15
Yes- I added in the Wikipedia cite option a while back on a whim, with intentions to go back and fix some of the bugs mentioned/do some extra testing. @jamiely  is it worth keeping this thread open until the bug(s) are fixed, or would you rather close this one and open a new one?

Thanks!

**Comment by jamiely** [comment] 2022-04-18 16:28
I'd rather open a new one, thanks!

**Closed by jamiely** 2022-04-18 16:28 UTC
